on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.repository }}
        tag_with_ref: true
        tag_whit_sha: true
        tags: ${{ secrets.sha }}
